"""
DOCUMENTACIÓN DE PAQUETE PYTHON_TOTAL_DOC:
    AUTOR: BJNM
    FECHA DE MODIFICACIÓN/CREACIÓN:
        * V1.0 --> 25/12/2021 (BJNM)
        * V1.1 --> 25/12/2021 (ABCD) 
    FUNCIONES INTERNAS: XYZ
    EXPLICACIÓN: ESTE ES UN PAQUETE SENCILLO EXPLICATIVO
"""