#INVOCACIÓN SENCILLA DE UN PAQUETE
from PYTHON_TOTAL.FUNCION_PAQUETE import *
FUNCT_PYTHON_TOTAL ()

#INVOCACIÓN SENCILLA DE UN SUBPAQUETE
from PYTHON_TOTAL.SUB_PYTHON_TOTAL.FUNCION_SUBPAQUETE import *
FUNCT_SUB_PYTHON_TOTAL ()